-- local json = require("json")

-- function on_event(event_json)
--     local event = json.decode(event_json)
--     print("Debug - Received event in Lua:", event_json)  -- Debug print
    
--     -- Check for Created, Updated, or Synced in the event table
--     if event.Created or event.Updated or event.Synced then
--         local metadata = {
--             tags = "example, lua, note",
--             summary = "Generated by Lua script"
--         }
--         local result = json.encode(metadata)
--         print("Debug - Returning metadata from Lua:", result)  -- Debug print
--         return result
--     end
    
--     return nil
-- end
